### ISSUE TITLE
Support Riverpod 2.0

### ISSUE THREAD

**Issue by klaasdannen** [quantosapplications/riverpod_messages#1]
please add Riverpod 2.0+ as an optional tag (or make it compatible with both versions). It just works, only dependency has to be changed, afaik.

**Comment by ftognetto** [comment]
Hi @klaasdannen finally riverpod has reached version 2.0.0 you can find the updated version of this package on pub.dev.
Thanks for using this package!

**Comment by klaasdannen** [comment]
Grazie for the quick fix only hours after the upstream package was released ;-)
